# Generated by Django 5.1.1 on 2024-09-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=55)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='products.producttype')),
                ('poducts', models.ManyToManyField(related_name='credits', to='products.product')),
            ],
        ),
    ]
