# Generated by Django 5.1.1 on 2024-09-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='products.client'),
        ),
    ]
